name: Tests

on: [push, pull_request]

jobs:
  pre-commit:
    strategy:
      matrix:
        python-version: ["3.8"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python  ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install pre-commit
          pip freeze
      - name: Run pre-commit
        run: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
  # docs:
  #   name: Documentation
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: ["3.8"]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python ${{ matrix.python-version }}
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - name: Install dependencies
  #       run: pip install tox
  #     - name: Check RST conformity with doc8
  #       run: tox -e doc8
  #     - name: Check docstring coverage
  #       run: tox -e docstr-coverage
  #     - name: Check documentation build with Sphinx
  #       run: tox -e docs
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
      - name: Install dependencies
        run: |
          sudo apt-get install libcgal-dev 
          conda install raspa2 zeopp-lsmo openbabel -c conda-forge -y
          pip install pytest &  pip install git+https://github.com/kjappelbaum/molecule-tda.git@refactor & pip install git+https://${{secrets.reporead}}@github.com/kjappelbaum/moffragmentor.git\
      - name: Install package
        run: pip install -e ".[all]"
      - name: Test with pytest
        run: |
          export RASPA_DIR=/usr/share/miniconda/envs/__setup_conda
          pytest tests/
